server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://8.137.116.121:8432/business_db
    username: business
    password: NewPass2024
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://admin:EurekaNew2024@localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: mySecretKeyForJWTTokenGenerationMustBeLongEnough12345
  expiration: 1800000
  refresh-expiration: 604800000

oidc:
  issuer: http://localhost:8081
  access-token-expiration: 1800000
  id-token-expiration: 3600000
  authorization-code-expiration: 600000

auth:
  register:
    invite-code-required: false
    invite-codes: ""
